# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logoImage', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mapImage', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MapHasLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIapp.Logo')),
                ('mapID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIapp.Map')),
            ],
        ),
        migrations.CreateModel(
            name='MapHasTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='maphastags',
            name='TagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIapp.Tag'),
        ),
        migrations.AddField(
            model_name='maphastags',
            name='mapID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIapp.Map'),
        ),
    ]
