# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='name',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='logoImage',
        ),
        migrations.AlterField(
            model_name='map',
            name='mapImage',
            field=models.ImageField(upload_to=b''),
        ),
    ]
